#pragma once

#include "parse/JCreateMap.h"
#include "parse/JSetManual.h"
#include "parse/JGetCurMapId.h"
#include "parse/JGetMapList.h"
#include "parse/JGetGridData.h"
#include "parse/JSetChangeScene.h"
#include "parse/JGetSceneDescInfo.h"
#include "parse/JAddSceneDescInfo.h"
#include "parse/JSerialData.h"
#include "parse/JSearchObj.h"
#include "parse/JSearchPeople.h"
#include "parse/JSearchPeopleUpdate.h"
#include "parse/JGetRobotState.h"
#include "parse/JTaskP2P.h"
#include "parse/JTaskFollow.h"
#include "parse/JTaskControl.h"
#include "parse/JTaskRecharge.h"
#include "parse/JTaskSemanticMove.h"
#include "parse/JTaskPatrol.h"

#include "parse/JReportBaseInfo.h"
#include "parse/JReportMapIncrement.h"
#include "parse/JReportPose.h"
#include "parse/JReportRoboticState.h"
#include "parse/JReportTaskState.h"
#include "parse/JReportIp.h"

#include "parse/JSubCmdVel.h"
